spring.application.name=lockly

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/lockly_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=lockly-super-secret-key-must-be-at-least-32-chars
jwt.access.expiration_time=3600000
jwt.refresh.expiration_time=604800000

# OTP
otp.expiration-minutes=5
otp.resend-cooldown-seconds=60

# Zalo (?? tr?ng khi dev)
zalo.oa.access-token=
zalo.oa.send-message-url=https://openapi.zalo.me/v3.0/oa/message/cs