name: Deploy Backend

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            khanhsayhi/lockly-backend:v2
            khanhsayhi/lockly-backend:${{ github.sha }}

      - name: Copy docker compose file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: docker-compose.yml
          target: /home/ubuntu/Backend/

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            cd /home/ubuntu/Backend

            docker login \
              -u "${{ secrets.DOCKERHUB_USERNAME }}" \
              -p "${{ secrets.DOCKERHUB_TOKEN }}"

            docker compose pull backend

            docker compose up -d --force-recreate backend